modLoader="javafml"
loaderVersion="[39,)"
license="All rights reserved"
issueTrackerURL="https://github.com/Linky132/WaywardCraft"
[[mods]]
modId="waywardcraft"
version="1.18.1-1.0.0"
displayName="WaywardCraft"
#updateJSONURL=""
#displayURL=""
#logoFile=""
credits="Credit and the rights for any concepts, characters, places, etc. that originate in Supernatural are property of The CW and/or any other relevant people who own the copyright to said concepts, characters, places, etc.."
authors="Linky132"
description='''
WaywardCraft is a mod that aims to bring all key concepts from the TV show Supernatural into Minecraft.
In this mod, you can live the life of a hunter, tracking down and killing ghosts, monsters, demons, angels, and more!

I do not own the rights to Supernatural, all credit for that goes to The CW and any other relevant parties.
'''
[[dependencies.waywardcraft]]
    modId="forge"
    mandatory=true
    versionRange="[38,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.waywardcraft]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.18,1.19)"
    ordering="NONE"
    side="BOTH"
[[dependencies.waywardcraft]]
    modId="geckolib3"
    mandatory=true
    versionRange="[1.18-forge-3.0.3,)"
    ordering="NONE"
    side="BOTH"